### ISSUE TITLE
purechat

### ISSUE THREAD

**Issue by dries-c** [EnderKenji/HealthTag#1]
not compatible with pure chat

**Comment by EnderKenji** [comment]
Do you mean want to add group beside name?

**Comment by dries-c** [comment]
No the nametag dont work server crasht
Op 12-dec.-2015 11:30 schreef "EnderKenji" notifications@github.com:

**Comment by EnderKenji** [comment]
Try download this version. 
http://mcpe-market.com/index.php?resources/healthtag.7/

**Comment by dries-c** [comment]
Do you have fix the bug
Op 12-dec.-2015 14:26 schreef "EnderKenji" notifications@github.com:
